config/routes.rb
Rails.application.routes.draw do
  resources :yard_sales

  get 'users/new'
  root 'sessions#new'
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/yard_sales' => 'high_voltage/pages#show', id: 'yard_sales'
  get '/home', to: redirect('/yard_sales')

  # root :to => 'high_voltage/pages#show', id: 'sessions#new'


  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/clothing_item.rb
class ClothingItem < Item

end

app/models/house_item.rb
class HouseItem < Item
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :yard_sale
	has_many :notes, as: :notable
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :notable, polymorphic: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  validates_presence_of :email
  validates_uniqueness_of :email
  after_create :welcome_email
  
  def welcome_email
    UserMailer.welcome_email(self)
  end
end

app/models/yard_sale.rb
class YardSale < ActiveRecord::Base
	has_many :clothing_items
	has_many :house_items

	validates_presence_of :name, :sale_date

  after_create :send_new_yard_sale_to_group

	scope :past_week, -> { where('sale_date > ?', 1.week.ago) }
  scope :latest, -> { order(:sale_date => :asc)}

  def send_new_yard_sale_to_group
    UserMailer.new_yard_sale_message_to_group(User.all, self)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :ensure_logged_in

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    if current_user.nil?
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #we don't want to ensure_logged-in yet, since we're just now creating the login session
  skip_filter :ensure_logged_in

  def new

  end

  def create
    user = User.find_by_email(params[:email]).try(:authenticate, params[:password])

    if user
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash.now.alert = "invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice:"You've logged-out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_filter :ensure_logged_in

  #GET '/users'
  def index
    #renders the new.html.page
  end

  def new
    @new_user = User.new
  end

  def create
    #How does this call user_mailer? It doesn't - the create yardsale does. See yard_sale.rb after_create method
    @new_user = User.new(user_params)
    if @new_user.save
      #tell the UserMailer to send a welcome email
      redirect_to login_path, notice: "Yeehaw! Thet thar's the seweeet smell of 'Signup Success''"
    else
      render :new, notice: "Sheeeooot! Yer Login done failed"
    end
  end

  def edit
    @user = User.update_attributes(params)
    if @user.save
      redirect_to show_user_path
    else
      redirect_to edit_user_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user.delete
  end

  private

  def user_params
    params.require(:user).permit!
  end
end

app/controllers/yard_sales_controller.rb
class YardSalesController < ApplicationController

	def index
		@yard_sales = YardSale.all.latest
	end

	def new
		@yard_sale = YardSale.new
	end

	def create
		# debugger
		@yard_sale = YardSale.new(yard_sale_params)
		if @yard_sale.save
			redirect_to yard_sales_path
		else
			render :new
		end
	end

	private 

	def yard_sale_params
		params.require(:yard_sale).permit!
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def site_name
    # Change the value below between the quotes.
    "Yard Sale App"
  end

  def site_url
    if Rails.env.production?
      # Place your production URL in the quotes below
      "http://http://www.example.com/"
    else
      # Our dev & test URL
      "http://localhost:3000"
    end
  end

  def meta_author
    # Change the value below between the quotes.
    "Website Author"
  end

  def meta_description
    # Change the value below between the quotes.
    "A student project: learning user authentication, mailers, and Bootstrap"
  end

  def meta_keywords
    # Change the value below between the quotes.
    "Add your keywords here"
  end

  # Returns the full title on a per-page basis.
  # No need to change any of this we set page_title and site_name elsewhere.
  def full_title(page_title)
    if page_title.empty?
      site_name
    else
      "#{page_title} | #{site_name}"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <a href="#Top"></a>
</head>
<body>
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to "Yard Sales", yard_sales_path, :class => "navbar-brand" %>

      </div>
      <div class="session-status">
      <% if current_user %>
        <%= "You're logged in as " + current_user.first_name + " " +current_user.last_name %>
        <%= link_to "Log Out", logout_path %>
      <% else %>
        <%= link_to "Log In", login_path %>
      <% end %>
      
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav pull-right">
          <!-- <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", yard_sales_path %></li> -->
          <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>          
          <li class="<%= 'active' if current_page?(yard_sales_path) %>"><%= link_to "Yard Sales", yard_sales_path %></li> 
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->

  <% if current_page?(root_path) %>
    <% if content_for?(:jumbotron) %>
      <div class="jumbotron">
        <div class="container">
          <%= yield :jumbotron %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="container-fluid">
  <% end %>
  <%= yield %>
  <footer>
    <hr>
      <p class="pull-right">
        <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
      </p>
      <p>
        &copy; <%= Time.now.year %> <%= site_name %> 
        &bull;
        <%= link_to "Privacy", privacy_path %></li>
        &bull;
        <%= link_to "Terms", terms_path %></li>
      </p>
    </footer>
  </div> <!-- /container -->
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About the Yard Sale App') %>
<div class="jumbotron">
  <p>Come and listen to a story about a man named Jed<br> 
  A poor mountaineer, barely kept his family fed,<br> 
  Then one day he was shootin at some food,<br> 
  And up through the ground came a bubblin crude.</p> 
  <p>
  Oil that is. Black gold. Texas tea. </p>
  <p>
  Well the first thing you know ol' Jed's a millionaire,<br> 
  Kin-folk said "Jed move away from there!" <br>
  Said "Californy is the place you oughtta be" <br>
  So they loaded up the truck and they moved to Beverly. </p>
  <p>
  Hills, that is. Swimmin' pools. Movie stars. </p>
  <p>
  Well now its time to say good-bye to Jed and all his kin.<br> 
  And they would like to thank you folks fer kindly droppin' in.<br> 
  You're all invited back a gain to this locality<br> 
  To have a heapin' helpin' of their hospitality </p>
  <p>
  Hillybilly that is. Set a spell. Take your shoes off.</p> 
  <p>
  Y'all come back now, y'hear?.
  </p>
</div>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact Us') %><h1>Contact Us</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<% provide(:title, '') %>
<% provide(:jumbotron, '
    <h1>Howdy Folks!</h1>
    <p><img class="img-left" src="/images/howdy.gif">This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>

    <a href="/sessions/destroy/">I\'m gonna get while the gettin\'s good!</a>

'.html_safe)%>

<%= link_to "logout", logout_path %>

app/views/pages/privacy.html.erb
<% provide(:title, 'Privacy Policy') %>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<% provide(:title, 'Site Usage Terms & Conditions') %>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/users/new.html.haml
%h2 Create/Sign-up New User
.centered
  = link_to "I already got me an account! Take me back twer I was.", new_session_path
%br
.col-md-6.col-md-offset-3
  = form_for(@new_user, url: users_path, html: {class: 'form-horizontal',  method: :post }) do |f|
    .form-group
    %label{:class => 'col-sm-4 control-label'} First Name:
    .col-sm-8
    = f.text_field :first_name, class: 'col-sm-8', autofocus: true
    .form-group
    %label{:class => 'col-sm-4 control-label'} Last Name:
    .col-sm-8
    = f.text_field :last_name, class: 'col-sm-8'
    .form-group
    %label{:class => 'col-sm-4 control-label'} Email:
    = f.email_field :email, class: 'col-sm-8'
    .form-group
    %label{:class => 'col-sm-4 control-label'} Password:
    = f.password_field :password, class: 'col-sm-8'
    .form-group
    %label{:class => 'col-sm-4 control-label'} Confirm Password:
    = f.password_field :password_confirmation, class: 'col-sm-8'
    .form-group
    = f.submit "Giddyup", class: 'col-sm-4 col-sm-offset-4'

app/views/users/show.html.haml
%h2 This here's all we know 'bout yuh
%div.span9
  %div.span9.offset3.centered
    %br
    = "You're logged in as " + "#{@user.first_name} #{@user.last_name}, an' we done got yer address as " + "#{@user.email}."  
    %br
    = "Now you can be sure we're gonna keep this here info classified."
    %br
    %div.bold
      = link_to "logout", logout_path
    

app/views/yard_sales/index.html.haml
%h2 These here yard sales are a-comin' up...

%ul.cards
  - @yard_sales.each do |ys|
    .flip
      .card
        .face.front
          = ys.name
        .face.back
          = ys.sale_date

.centered.double-size   
  = link_to ("Holler about yer own yard sale"), new_yard_sale_path

app/views/yard_sales/new.html.haml
%h2 Got a hankerin' tuh host yerself a yard sale?
%hr
.wow-form
  =form_for(@yard_sale, url: {action: "create"}, html: {class: "new_sale_form", method: :post })  do |f|
    %br
    = f.label :"What yer gonna call it?"
    = f.text_field :name, :autofocus => true
    %br
    %br
    = f.label :"When's it gonna be?"
    = f.date_field :sale_date
    %br
    = f.submit "Git 'er done!"